apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bkci-dispatch
  name: bkci-dispatch
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bkci-dispatch
  template:
    metadata:
      labels:
        app: bkci-dispatch
    spec:
      containers:
        - image: {{ .Values.image.hub }}/bkci-dispatch:{{ .Values.image.tag }} 
          name: bkci-dispatch
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /data/docker/bkci/ci/backend/
          command: ['/bin/sh','-c','/data/docker/bkci/ci/backend/module_run.sh']