apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-environment
  labels:
    pv: nfs-environment
spec:
  capacity:
    storage: {{ .Values.volume.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.volume.persistentVolumeReclaimPolicy }}
  storageClassName: nfs-environment
  nfs:
    path: /data/nfs/environment
    server: {{ .Values.volume.nfs.server }}
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-environment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.storage }}
  storageClassName: nfs-environment
  selector:
    matchLabels:
      pv: nfs-environment
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bkci-environment
  name: bkci-environment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bkci-environment
  template:
    metadata:
      labels:
        app: bkci-environment
    spec:
      containers:
        - image: {{ .Values.image.hub }}/bkci-environment:{{ .Values.image.tag }}
          name: bkci-environment
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /data/docker/bkci/ci/backend/
          command: 
            - '/bin/sh'
            - '-c'
            - 'ln -s /data/docker/bkci/public/ci/environment/packages /data/docker/bkci/ci/agent-package/packages ; 
               ln -s /data/docker/bkci/public/ci/environment/jre /data/docker/bkci/ci/agent-package/jre ;
               /data/docker/bkci/ci/backend/module_run.sh'
          volumeMounts:
            - mountPath: "/data/docker/bkci/public/ci/environment"
              name: nfs-environment
      volumes: 
        - name: nfs-environment
          persistentVolumeClaim: 
            claimName: nfs-environment