apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bkci-gateway
  name: bkci-gateway
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bkci-gateway
  template:
    metadata:
      labels:
        app: bkci-gateway
    spec:
      containers:
        - image: {{ .Values.image.hub }}/gateway:{{ .Values.image.tag }}
          name: bkci-gateway
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /usr/local/openresty/nginx/
          command: ['/bin/sh','-c','/data/docker/bkci/ci/gateway/gateway_run.sh']
---
apiVersion: v1
kind: Service
metadata:
  name: bkci-gateway
spec:
  selector:
    app: bkci-gateway
  ports:
    - protocol: TCP
      port: 80